# -*- coding: utf-8 -*-

"""
billbeeapi

This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class AddressTypeEnum(object):

    """Implementation of the 'AddressType' enum.

    The type of the address

    Attributes:
        ENUM_1: TODO: type description here.
        ENUM_2: TODO: type description here.

    """

    ENUM_1 = 1

    ENUM_2 = 2
