# -*- coding: utf-8 -*-

"""
billbeeapi

This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class BillbeeInterfacesBillbeeAPIModelArticleCategoryApiModel(object):

    """Implementation of the 'Billbee.Interfaces.BillbeeAPI.Model.ArticleCategoryApiModel' model.

    TODO: type model description here.

    Attributes:
        name (string): TODO: type description here.
        id (long|int): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "name": 'Name',
        "id": 'Id'
    }

    def __init__(self,
                 name=None,
                 id=None):
        """Constructor for the BillbeeInterfacesBillbeeAPIModelArticleCategoryApiModel class"""

        # Initialize members of the class
        self.name = name
        self.id = id

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        name = dictionary.get('Name')
        id = dictionary.get('Id')

        # Return an object of this model
        return cls(name,
                   id)
