"""
billbeeapi

This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class BillbeeInterfacesShippingShipmentDataDimensions:

    """Implementation of the 'Billbee.Interfaces.Shipping.ShipmentData.Dimensions' model.

    TODO: type model description here.

    Attributes:
        length (float): TODO: type description here.
        width (float): TODO: type description here.
        height (float): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {"length": "length", "width": "width", "height": "height"}

    def __init__(self, length=None, width=None, height=None):
        """Constructor for the BillbeeInterfacesShippingShipmentDataDimensions class"""

        # Initialize members of the class
        self.length = length
        self.width = width
        self.height = height

    @classmethod
    def from_dictionary(cls, dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        length = dictionary.get("length")
        width = dictionary.get("width")
        height = dictionary.get("height")

        # Return an object of this model
        return cls(length, width, height)
