"""
billbeeapi

This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class BillbeeInterfacesBillbeeAPIModelGetReservedAmountResponseData:

    """Implementation of the 'Billbee.Interfaces.BillbeeAPI.Model.GetReservedAmountResponseData' model.

    TODO: type model description here.

    Attributes:
        reserved_amount (float): The reserve (not fulfilled) qty of the
            article

    """

    # Create a mapping from Model property names to API property names
    _names = {"reserved_amount": "ReservedAmount"}

    def __init__(self, reserved_amount=None):
        """Constructor for the BillbeeInterfacesBillbeeAPIModelGetReservedAmountResponseData class"""

        # Initialize members of the class
        self.reserved_amount = reserved_amount

    @classmethod
    def from_dictionary(cls, dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        reserved_amount = dictionary.get("ReservedAmount")

        # Return an object of this model
        return cls(reserved_amount)
