"""
billbeeapi

This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""
from billbeeapi.api_helper import APIHelper


class BillbeeInterfacesBillbeeAPIModelCommentApiModel:

    """Implementation of the 'Billbee.Interfaces.BillbeeAPI.Model.CommentApiModel' model.

    TODO: type model description here.

    Attributes:
        id (long|int): TODO: type description here.
        from_customer (bool): TODO: type description here.
        text (string): TODO: type description here.
        name (string): TODO: type description here.
        created (datetime): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {"id": "Id", "from_customer": "FromCustomer", "text": "Text", "name": "Name", "created": "Created"}

    def __init__(self, id=None, from_customer=None, text=None, name=None, created=None):
        """Constructor for the BillbeeInterfacesBillbeeAPIModelCommentApiModel class"""

        # Initialize members of the class
        self.id = id
        self.from_customer = from_customer
        self.text = text
        self.name = name
        self.created = APIHelper.RFC3339DateTime(created) if created else None

    @classmethod
    def from_dictionary(cls, dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        id = dictionary.get("Id")
        from_customer = dictionary.get("FromCustomer")
        text = dictionary.get("Text")
        name = dictionary.get("Name")
        created = (
            APIHelper.RFC3339DateTime.from_value(dictionary.get("Created")).datetime
            if dictionary.get("Created")
            else None
        )

        # Return an object of this model
        return cls(id, from_customer, text, name, created)
