"""
billbeeapi

This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class BillbeeInterfacesBillbeeAPIModelShipmentAddressApiModel:

    """Implementation of the 'Billbee.Interfaces.BillbeeAPI.Model.ShipmentAddressApiModel' model.

    TODO: type model description here.

    Attributes:
        company (string): TODO: type description here.
        first_name (string): TODO: type description here.
        last_name (string): TODO: type description here.
        name_2 (string): TODO: type description here.
        street (string): TODO: type description here.
        housenumber (string): TODO: type description here.
        zip (string): TODO: type description here.
        city (string): TODO: type description here.
        country_code (string): TODO: type description here.
        country_code_iso_3 (string): TODO: type description here.
        email (string): TODO: type description here.
        telephone (string): TODO: type description here.
        address_addition (string): TODO: type description here.
        is_export_country (bool): TODO: type description here.
        state (string): TODO: type description here.
        full_name (string): TODO: type description here.
        full_street (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "company": "Company",
        "first_name": "FirstName",
        "last_name": "LastName",
        "name_2": "Name2",
        "street": "Street",
        "housenumber": "Housenumber",
        "zip": "Zip",
        "city": "City",
        "country_code": "CountryCode",
        "country_code_iso_3": "CountryCodeISO3",
        "email": "Email",
        "telephone": "Telephone",
        "address_addition": "AddressAddition",
        "is_export_country": "IsExportCountry",
        "state": "State",
        "full_name": "FullName",
        "full_street": "FullStreet",
    }

    def __init__(
        self,
        company=None,
        first_name=None,
        last_name=None,
        name_2=None,
        street=None,
        housenumber=None,
        zip=None,
        city=None,
        country_code=None,
        country_code_iso_3=None,
        email=None,
        telephone=None,
        address_addition=None,
        is_export_country=None,
        state=None,
        full_name=None,
        full_street=None,
    ):
        """Constructor for the BillbeeInterfacesBillbeeAPIModelShipmentAddressApiModel class"""

        # Initialize members of the class
        self.company = company
        self.first_name = first_name
        self.last_name = last_name
        self.name_2 = name_2
        self.street = street
        self.housenumber = housenumber
        self.zip = zip
        self.city = city
        self.country_code = country_code
        self.country_code_iso_3 = country_code_iso_3
        self.email = email
        self.telephone = telephone
        self.address_addition = address_addition
        self.is_export_country = is_export_country
        self.state = state
        self.full_name = full_name
        self.full_street = full_street

    @classmethod
    def from_dictionary(cls, dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        company = dictionary.get("Company")
        first_name = dictionary.get("FirstName")
        last_name = dictionary.get("LastName")
        name_2 = dictionary.get("Name2")
        street = dictionary.get("Street")
        housenumber = dictionary.get("Housenumber")
        zip = dictionary.get("Zip")
        city = dictionary.get("City")
        country_code = dictionary.get("CountryCode")
        country_code_iso_3 = dictionary.get("CountryCodeISO3")
        email = dictionary.get("Email")
        telephone = dictionary.get("Telephone")
        address_addition = dictionary.get("AddressAddition")
        is_export_country = dictionary.get("IsExportCountry")
        state = dictionary.get("State")
        full_name = dictionary.get("FullName")
        full_street = dictionary.get("FullStreet")

        # Return an object of this model
        return cls(
            company,
            first_name,
            last_name,
            name_2,
            street,
            housenumber,
            zip,
            city,
            country_code,
            country_code_iso_3,
            email,
            telephone,
            address_addition,
            is_export_country,
            state,
            full_name,
            full_street,
        )
