"""
billbeeapi

This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class BillbeeInterfacesBillbeeAPIModelDeletedImagesModel:

    """Implementation of the 'Billbee.Interfaces.BillbeeAPI.Model.DeletedImagesModel' model.

    TODO: type model description here.

    Attributes:
        deleted (list of long|int): TODO: type description here.
        not_found (list of long|int): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {"deleted": "Deleted", "not_found": "NotFound"}

    def __init__(self, deleted=None, not_found=None):
        """Constructor for the BillbeeInterfacesBillbeeAPIModelDeletedImagesModel class"""

        # Initialize members of the class
        self.deleted = deleted
        self.not_found = not_found

    @classmethod
    def from_dictionary(cls, dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        deleted = dictionary.get("Deleted")
        not_found = dictionary.get("NotFound")

        # Return an object of this model
        return cls(deleted, not_found)
