# -*- coding: utf-8 -*-

"""
billbeeapi

This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class PaymentMethodEnum(object):

    """Implementation of the 'PaymentMethod' enum.

    The payment method

    Attributes:
        ENUM_1: TODO: type description here.
        ENUM_2: TODO: type description here.
        ENUM_3: TODO: type description here.
        ENUM_4: TODO: type description here.
        ENUM_6: TODO: type description here.
        ENUM_19: TODO: type description here.
        ENUM_20: TODO: type description here.
        ENUM_21: TODO: type description here.
        ENUM_22: TODO: type description here.
        ENUM_23: TODO: type description here.
        ENUM_24: TODO: type description here.
        ENUM_25: TODO: type description here.
        ENUM_26: TODO: type description here.
        ENUM_27: TODO: type description here.
        ENUM_28: TODO: type description here.
        ENUM_29: TODO: type description here.
        ENUM_30: TODO: type description here.
        ENUM_31: TODO: type description here.
        ENUM_32: TODO: type description here.
        ENUM_33: TODO: type description here.
        ENUM_34: TODO: type description here.
        ENUM_35: TODO: type description here.
        ENUM_36: TODO: type description here.
        ENUM_37: TODO: type description here.
        ENUM_38: TODO: type description here.
        ENUM_39: TODO: type description here.
        ENUM_40: TODO: type description here.
        ENUM_41: TODO: type description here.
        ENUM_42: TODO: type description here.
        ENUM_43: TODO: type description here.
        ENUM_44: TODO: type description here.
        ENUM_45: TODO: type description here.
        ENUM_46: TODO: type description here.
        ENUM_47: TODO: type description here.
        ENUM_48: TODO: type description here.
        ENUM_49: TODO: type description here.
        ENUM_50: TODO: type description here.
        ENUM_51: TODO: type description here.
        ENUM_52: TODO: type description here.
        ENUM_53: TODO: type description here.
        ENUM_54: TODO: type description here.
        ENUM_55: TODO: type description here.
        ENUM_56: TODO: type description here.
        ENUM_57: TODO: type description here.
        ENUM_58: TODO: type description here.
        ENUM_59: TODO: type description here.
        ENUM_60: TODO: type description here.
        ENUM_61: TODO: type description here.
        ENUM_62: TODO: type description here.
        ENUM_63: TODO: type description here.
        ENUM_64: TODO: type description here.
        ENUM_65: TODO: type description here.
        ENUM_66: TODO: type description here.
        ENUM_67: TODO: type description here.
        ENUM_68: TODO: type description here.
        ENUM_69: TODO: type description here.
        ENUM_70: TODO: type description here.
        ENUM_71: TODO: type description here.
        ENUM_72: TODO: type description here.
        ENUM_73: TODO: type description here.
        ENUM_74: TODO: type description here.
        ENUM_75: TODO: type description here.
        ENUM_76: TODO: type description here.
        ENUM_77: TODO: type description here.
        ENUM_78: TODO: type description here.
        ENUM_79: TODO: type description here.
        ENUM_80: TODO: type description here.
        ENUM_81: TODO: type description here.
        ENUM_82: TODO: type description here.
        ENUM_83: TODO: type description here.
        ENUM_84: TODO: type description here.
        ENUM_85: TODO: type description here.
        ENUM_86: TODO: type description here.
        ENUM_87: TODO: type description here.
        ENUM_88: TODO: type description here.
        ENUM_89: TODO: type description here.
        ENUM_90: TODO: type description here.
        ENUM_91: TODO: type description here.
        ENUM_92: TODO: type description here.
        ENUM_93: TODO: type description here.
        ENUM_94: TODO: type description here.
        ENUM_95: TODO: type description here.
        ENUM_96: TODO: type description here.
        ENUM_97: TODO: type description here.
        ENUM_98: TODO: type description here.
        ENUM_99: TODO: type description here.
        ENUM_100: TODO: type description here.
        ENUM_101: TODO: type description here.
        ENUM_102: TODO: type description here.
        ENUM_103: TODO: type description here.
        ENUM_104: TODO: type description here.
        ENUM_105: TODO: type description here.
        ENUM_106: TODO: type description here.
        ENUM_107: TODO: type description here.
        ENUM_108: TODO: type description here.
        ENUM_109: TODO: type description here.
        ENUM_110: TODO: type description here.
        ENUM_111: TODO: type description here.
        ENUM_112: TODO: type description here.

    """

    ENUM_1 = 1

    ENUM_2 = 2

    ENUM_3 = 3

    ENUM_4 = 4

    ENUM_6 = 6

    ENUM_19 = 19

    ENUM_20 = 20

    ENUM_21 = 21

    ENUM_22 = 22

    ENUM_23 = 23

    ENUM_24 = 24

    ENUM_25 = 25

    ENUM_26 = 26

    ENUM_27 = 27

    ENUM_28 = 28

    ENUM_29 = 29

    ENUM_30 = 30

    ENUM_31 = 31

    ENUM_32 = 32

    ENUM_33 = 33

    ENUM_34 = 34

    ENUM_35 = 35

    ENUM_36 = 36

    ENUM_37 = 37

    ENUM_38 = 38

    ENUM_39 = 39

    ENUM_40 = 40

    ENUM_41 = 41

    ENUM_42 = 42

    ENUM_43 = 43

    ENUM_44 = 44

    ENUM_45 = 45

    ENUM_46 = 46

    ENUM_47 = 47

    ENUM_48 = 48

    ENUM_49 = 49

    ENUM_50 = 50

    ENUM_51 = 51

    ENUM_52 = 52

    ENUM_53 = 53

    ENUM_54 = 54

    ENUM_55 = 55

    ENUM_56 = 56

    ENUM_57 = 57

    ENUM_58 = 58

    ENUM_59 = 59

    ENUM_60 = 60

    ENUM_61 = 61

    ENUM_62 = 62

    ENUM_63 = 63

    ENUM_64 = 64

    ENUM_65 = 65

    ENUM_66 = 66

    ENUM_67 = 67

    ENUM_68 = 68

    ENUM_69 = 69

    ENUM_70 = 70

    ENUM_71 = 71

    ENUM_72 = 72

    ENUM_73 = 73

    ENUM_74 = 74

    ENUM_75 = 75

    ENUM_76 = 76

    ENUM_77 = 77

    ENUM_78 = 78

    ENUM_79 = 79

    ENUM_80 = 80

    ENUM_81 = 81

    ENUM_82 = 82

    ENUM_83 = 83

    ENUM_84 = 84

    ENUM_85 = 85

    ENUM_86 = 86

    ENUM_87 = 87

    ENUM_88 = 88

    ENUM_89 = 89

    ENUM_90 = 90

    ENUM_91 = 91

    ENUM_92 = 92

    ENUM_93 = 93

    ENUM_94 = 94

    ENUM_95 = 95

    ENUM_96 = 96

    ENUM_97 = 97

    ENUM_98 = 98

    ENUM_99 = 99

    ENUM_100 = 100

    ENUM_101 = 101

    ENUM_102 = 102

    ENUM_103 = 103

    ENUM_104 = 104

    ENUM_105 = 105

    ENUM_106 = 106

    ENUM_107 = 107

    ENUM_108 = 108

    ENUM_109 = 109

    ENUM_110 = 110

    ENUM_111 = 111

    ENUM_112 = 112
