# -*- coding: utf-8 -*-

"""
billbeeapi

This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class RechnungsdruckWebAppControllersApiOrderTagCreate(object):

    """Implementation of the 'Rechnungsdruck.WebApp.Controllers.Api.OrderTagCreate' model.

    TODO: type model description here.

    Attributes:
        tags (list of string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "tags": 'Tags'
    }

    def __init__(self,
                 tags=None):
        """Constructor for the RechnungsdruckWebAppControllersApiOrderTagCreate class"""

        # Initialize members of the class
        self.tags = tags

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        tags = dictionary.get('Tags')

        # Return an object of this model
        return cls(tags)
